// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	TimerDelayValue(ctx context.Context, in *DelayValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSortByAverageSalary(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*AverageSalaryResponse, error)
	GetSortOldestAndHighestPaid(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*OldestAndHighestPaidResponse, error)
	GetSortByValue(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*UserParameterListResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) TimerDelayValue(ctx context.Context, in *DelayValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.User/TimerDelayValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSortByAverageSalary(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*AverageSalaryResponse, error) {
	out := new(AverageSalaryResponse)
	err := c.cc.Invoke(ctx, "/proto.User/GetSortByAverageSalary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSortOldestAndHighestPaid(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*OldestAndHighestPaidResponse, error) {
	out := new(OldestAndHighestPaidResponse)
	err := c.cc.Invoke(ctx, "/proto.User/GetSortOldestAndHighestPaid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSortByValue(ctx context.Context, in *UserParameterListWithSortValueRequest, opts ...grpc.CallOption) (*UserParameterListResponse, error) {
	out := new(UserParameterListResponse)
	err := c.cc.Invoke(ctx, "/proto.User/GetSortByValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	TimerDelayValue(context.Context, *DelayValue) (*emptypb.Empty, error)
	GetSortByAverageSalary(context.Context, *UserParameterListWithSortValueRequest) (*AverageSalaryResponse, error)
	GetSortOldestAndHighestPaid(context.Context, *UserParameterListWithSortValueRequest) (*OldestAndHighestPaidResponse, error)
	GetSortByValue(context.Context, *UserParameterListWithSortValueRequest) (*UserParameterListResponse, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) TimerDelayValue(context.Context, *DelayValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimerDelayValue not implemented")
}
func (UnimplementedUserServer) GetSortByAverageSalary(context.Context, *UserParameterListWithSortValueRequest) (*AverageSalaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSortByAverageSalary not implemented")
}
func (UnimplementedUserServer) GetSortOldestAndHighestPaid(context.Context, *UserParameterListWithSortValueRequest) (*OldestAndHighestPaidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSortOldestAndHighestPaid not implemented")
}
func (UnimplementedUserServer) GetSortByValue(context.Context, *UserParameterListWithSortValueRequest) (*UserParameterListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSortByValue not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_TimerDelayValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelayValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).TimerDelayValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/TimerDelayValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).TimerDelayValue(ctx, req.(*DelayValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSortByAverageSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserParameterListWithSortValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSortByAverageSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/GetSortByAverageSalary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSortByAverageSalary(ctx, req.(*UserParameterListWithSortValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSortOldestAndHighestPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserParameterListWithSortValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSortOldestAndHighestPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/GetSortOldestAndHighestPaid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSortOldestAndHighestPaid(ctx, req.(*UserParameterListWithSortValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSortByValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserParameterListWithSortValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSortByValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/GetSortByValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSortByValue(ctx, req.(*UserParameterListWithSortValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TimerDelayValue",
			Handler:    _User_TimerDelayValue_Handler,
		},
		{
			MethodName: "GetSortByAverageSalary",
			Handler:    _User_GetSortByAverageSalary_Handler,
		},
		{
			MethodName: "GetSortOldestAndHighestPaid",
			Handler:    _User_GetSortOldestAndHighestPaid_Handler,
		},
		{
			MethodName: "GetSortByValue",
			Handler:    _User_GetSortByValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
